### ISSUE TITLE
Look to upgrade to wasmer v2.0.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/wasm#20]
https://wasmer.io/posts/wasmer-2.0

V2 is out.

I tried. Tests don't work. But worth investigating.

**Comment by kevmoo** [comment]
Thoughts on this @liamappelbe ?

**Comment by liamappelbe** [comment]
Makes sense. I'll get to it eventually. Not a high priority though since, in theory, it shouldn't change anything from the user's perspective (we're not exposing SIMD or reference types currently).

**Comment by kevmoo** [comment]
Riiiight
