### ISSUE TITLE
missing API to set guest globals

### ISSUE THREAD

**Issue by maks** [dart-lang/wasm#24]
I would like to set a guest global as [described in the wasmer documentation](https://docs.wasmer.io/integrations/examples/using-exported-globals#setting-globals), so in C it would be using `wasm_global_set()` but I can't find how I can do that using this packages API or am I missing something obvious?

**Comment by liamappelbe** [comment]
No, you're not missing anything. I haven't wrapped all the wasmer functions yet because I didn't have a use case. This feature will be easy to add.

**Comment by maks** [comment]
@liamappelbe that's great news, thanks! 

For a bit of context on my usecase if it helps: as part of a larger audio project, I'm  building a [synthesizer in Dart ](https://github.com/maks/dart_synth) which is using [audio/DSP code written in AssemblyScript](https://github.com/maks/as-audio), which comes from a different developers [web-based project](https://github.com/petersalomonsen/javascriptmusic/tree/master/wasmaudioworklet/synth1/assembly). Some of his AS code uses globals to allow the wasm host to set/get some parameters used in the AS code, like [samplerate](https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/synth1/assembly/environment.ts).
