### ISSUE TITLE
plans for publishing on pub?

### ISSUE THREAD

**Issue by maks** [dart-lang/wasm#30]
I know this package is still very new but I wanted to check on what the plans are for publishing it on pub? 

I ask as I already have a [small package](https://github.com/maks/dart_synth) that is making successful use of it, but because its using this package as a git dependency, I'm blocked from publishing my package on pub as well.

**Comment by mit-mit** [comment]
Yes, hopefully soon. We just had to work through some last issues.

**Comment by liamappelbe** [comment]
It's published: https://pub.dev/packages/wasm
