### ISSUE TITLE
createGlobal is not defined

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/wasm#35]
The description of `WasmGlobal` refers to undefined `WasmModule.createGlobal` methods:
https://github.com/dart-lang/wasm/blob/c29808a450488fa139e6173386444f18ca676317/lib/src/module.dart#L427-L430

**Comment by liamappelbe** [comment]
Oh, yeah, I changed the api and then forgot to update the comment. `test/globals_test.dart` shows how to use it. `WasmInstanceBuilder.addGlobal` returns the global it created. I'll fix the comment.
